### PR TITLE
Added Hungarian Translation

### PR DESCRIPTION
**Pull request by ferivoq**
Added app_hu.arb.
A Hungarian Translation of PsTube

### CODE REVIEW

**Comment by prateekmedia** [comment]
Thanks for this but can you add the translations to the weblate as we use that for translations.

**Comment by ferivoq** [comment]
Oh ok

**Comment by ferivoq** [comment]
I did it. On that site. Will I have Credit for translating?

**Comment by prateekmedia** [comment]
Yes on the app about dialog, I will update it when releasing the new version.

**Pull request closed without merging**
