### PR TITLE
Draft: initial media kit support

### PR DESCRIPTION
**Pull request by Quackdoc**
Very WIP support for media_kit, based on the new https://github.com/alexmercerind/media_kit which can be thought of the successor to dart_vlc, it already out preforms dart_vlc for high resolution content as well as supporting hwdecode. currently can load a video and play it back using a very basic taskbar. good enough for testing. 

not sure when I'll have the time to finish this up and clean it up, but media_kit support for Linux and OSX is still lacking anyways and I assume those are major blockers in any case.
 

- [x]  Windows support
- [x] Support for Split streaming (1080p+ resolution)
- [ ] Linux support
- [ ] OSX support
- [ ] Better control system
- [ ] stability

### CODE REVIEW

**Comment by Quackdoc** [comment]
ive updated the PR to use the github media_kit now, so users on windows will be able to do some intial testing

**Comment by Quackdoc** [comment]
media_kit now has linux support, I plan to add it in the comming days, it should be a simple add. once done the only necessary features will be 

* fullscreen
* audio control
* resolution select

**Comment by Quackdoc** [comment]
osx support is now being worked on in media_kit.

**Review by prateekmedia — APPROVED** [review]
Merging this so that we can work upon this!

**Comment by Quackdoc** [comment]
sorry for not being able to work on it more, hopefully ill have some more time to contribute in the future.

**Comment by prateekmedia** [comment]
@Quackdoc I am not sure but this is what I am getting in the latest commit for any video I play, what do you think I am missing?
image

**Comment by prateekmedia** [comment]
@Quackdoc this is what I am getting with the latest commit:
image

**Comment by Quackdoc** [comment]
> @Quackdoc this is what I am getting with the latest commit, am I missing something?

use the stable, I haven't been involved in media_kit for a bit of time while I am busy, but I quickly span up a build and mpv was erroring out

```
  media_kit: ^0.0.4
  media_kit_video: ^0.0.4
  media_kit_native_event_loop: ^1.0.2
  media_kit_libs_windows_video: ^1.0.1 
  media_kit_libs_linux: ^1.0.1 
```

this loads fine

**Pull request merged**
